### ISSUE TITLE
주인공의 체력 및 피격 관련

### ISSUE THREAD

**Issue by kaelo1205** [223344xxc/Dant#9]
주 내용 : 주인공이 공격을 받고, 그에 대한 결과 처리

주인공의 체력은 기본적으로 세칸입니다.
체력이 세칸 이하가 된다면 사망 처리 -> 게임 정지 -> 결과 창을 띄우면 될 듯 합니다.

주인공의 체력이 감소되는 경우는 두가지가 있습니다.
1. 적 몬스터에게 피격시 감소
2. 절벽에서 떨어질 경우 감소

1번의 경우에는 현재 적 몬스터가 애벌레밖에 없으니, 일단 접촉시 피격 처리를 해주시면 됩니다.
+ 피격 당할 시 주인공이 3초간 깜빡이며(투명도) 무적 상태였으면 좋겠습니다. 무적 시간이 끝나갈수록 빨리 깜빡이면 좋겠습니다.
+ 강한 화면 흔들림이 있으면 좋겠습니다.

2번의 경우에는 체력 감소 후 떨어진 위치에서 가장 가까운 곳으로 리스폰 해주시면 됩니다.
+ 낑김 버그가 있을 수도 있으니, 지면에서 약간 높은 곳에 리스폰 해주시면 좋겠습니다.
+ 1번과 같이 무적 상태이지만, 정확히 리스폰 된 시점부터 무적이어야 할 듯 합니다.

**Comment by 0b00101010** [comment]
2번의 경우 추락 이후 위치 복귀 한 시점에는 무적 처리 어떻게 처리 할 지 또한 전달해주셨으면합니다.
